---
- name: Deploying Apache container
  hosts: node1
  become: true
  vars_files:
    files/secrets/credentials.vault
  pre_tasks:
  - name: install pip {{ansible_password}}
    yum:
      name: python-pip
      state: present
      update_cache: yes
  - name: install python library for docker {{ task_name }}
    pip:
      name: docker
      extra_args: --ignore-installed requests
  - name: install docker with python
    yum:
      name: docker
      state: present
  - name: start docker daemon
    service:
      name: docker
      state: started
  tasks:
  - name: create apache container
    docker_container:
      name: webapp
      image: httpd
      ports: "90:80"
      volumes:
        - /home/ec2-user/index.html:/usr/local/apache2/htdocs/index.html
  - name: template the index html
    template:
      src: index.html.j2
      dest: /home/ec2-user/index.html
  - name: install git and wget
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - wget
    when:
      ansible_distribution == "CentOs"
